### ISSUE TITLE
Edit Study Materials

### ISSUE THREAD

**Issue by nowa5285** [coconnor0803/csci3308team015-06#16]
As a user, I want to be able to edit the terms and definitions of study materials I have uploaded, so that I can refine and update the content to better align with my learning needs.

Acceptance Criteria:
As a user, I should be able to edit the terms and definitions of study materials I have uploaded.
As a user, the editing process should be intuitive and user-friendly.
As a user, I should be able to save my changes and see them reflected in the study materials.

**Comment by nowa5285** [comment]
Added ability to edit uploaded sets with upload function for second and week before last week

**Comment by coconnor0803** [comment]
The user is able to add a new term to the study set from the view/edit page. This was implemented 4/25.
