### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by nowa5285** [coconnor0803/csci3308team015-06#5]
As a user, I want to be able to securely log in to my account using my registered email and password, ensuring that only authorized users can access their accounts.

Acceptance Criteria:
As a user, I should be able to log in using my registered email and password.
As a user, incorrect login attempts should prompt appropriate error messages.
As a user, upon successful login, I should be directed to my dashboard or homepage.

**Comment by coconnor0803** [comment]
The login was implemented on April 11th. The user is able to successfully login and or register and is sent to the home page to then interact with the website.
